[package]
name = "unit-rs-app"
version = "0.2.0-alpha3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unit-rs = "0.1"
